version: '1.1'

include:
  - proxy.yaml

services:
  db:
    image: mysql/mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_HOST: "%"
    networks:
      backend:
        ipv4_address: 172.20.0.10
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./mysql:/var/lib/mysql

  web:
    image: python/webapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
        - DB_USER=$MYSQL_USER
        - DB_PASSWORD=$MYSQL_PASSWORD
        - DB_NAME=$MYSQL_DATABASE
        - DB_HOST=db
        - DB_TABLE=requests
    depends_on:
      - db
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.5
    ports:
      - "5000:5000"
