version: '1.1'
services:
  bd:
    image: mysql/mysql-server
    restart: always
    networks:
      - app
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./mysql:/var/lib/mysql

  app:
    image: python/webapp
    build:
      dockerfile: ./Dockerfile
      args:
        - DB_USER=$MYSQL_USER
        - DB_PASSWORD=$MYSQL_PASSWORD
        - DB_NAME=$MYSQL_DATABASE
    depends_on:
      - bd
    restart: always
    ports:
      - "5000:5000"
    networks:
      - app

networks:
  app:
    driver: bridge